// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ConnectWalletButton: typeof import('./src/components/ConnectWalletButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IMdiBrightness4: typeof import('~icons/mdi/brightness4')['default']
    IMdiBrightness7: typeof import('~icons/mdi/brightness7')['default']
    IMdiC: typeof import('~icons/mdi/c')['default']
    IMdiChartLine: typeof import('~icons/mdi/chart-line')['default']
    IMdiCloud: typeof import('~icons/mdi/cloud')['default']
    IMdiCog: typeof import('~icons/mdi/cog')['default']
    IMdiComputer: typeof import('~icons/mdi/computer')['default']
    IMdiComputerTower: typeof import('~icons/mdi/computer-tower')['default']
    IMdiComputerTowerBold: typeof import('~icons/mdi/computer-tower-bold')['default']
    IMdiDashboard: typeof import('~icons/mdi/dashboard')['default']
    IMdiDashboardFill: typeof import('~icons/mdi/dashboard-fill')['default']
    IMdiDatabase: typeof import('~icons/mdi/database')['default']
    IMdiFileOutline: typeof import('~icons/mdi/file-outline')['default']
    IMdiFlashOutline: typeof import('~icons/mdi/flash-outline')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    IMdiHomeStorage: typeof import('~icons/mdi/home-storage')['default']
    IMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IMdiMdiStackoverflow: typeof import('~icons/mdi/mdi-stackoverflow')['default']
    IMdiStackoverflow: typeof import('~icons/mdi/stackoverflow')['default']
    IMdiStorage: typeof import('~icons/mdi/storage')['default']
    IMdiTachometer: typeof import('~icons/mdi/tachometer')['default']
    IMdiTachometerAlt: typeof import('~icons/mdi/tachometer-alt')['default']
    IMdiTimerSand: typeof import('~icons/mdi/timer-sand')['default']
    IMdiUpload: typeof import('~icons/mdi/upload')['default']
    IMdiViewDashboard: typeof import('~icons/mdi/view-dashboard')['default']
    IMdiVolumeObjectStorage: typeof import('~icons/mdi/volume-object-storage')['default']
    IRiClipboardLine: typeof import('~icons/ri/clipboard-line')['default']
    IRiExternalLinkFill: typeof import('~icons/ri/external-link-fill')['default']
    IRiFileList3Line: typeof import('~icons/ri/file-list3-line')['default']
    PanelResult: typeof import('./src/components/PanelResult.vue')['default']
    PanelUpload: typeof import('./src/components/PanelUpload.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResult: typeof import('./src/components/SearchResult.vue')['default']
    SidebarView: typeof import('./src/components/SidebarView.vue')['default']
  }
}
