// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ConnectWalletButton: typeof import('./src/components/ConnectWalletButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IMdiBrightness4: typeof import('~icons/mdi/brightness4')['default']
    IMdiBrightness7: typeof import('~icons/mdi/brightness7')['default']
    IMdiFlashOutline: typeof import('~icons/mdi/flash-outline')['default']
    IMdiTimerSand: typeof import('~icons/mdi/timer-sand')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
